urls.py
# -*- coding: utf-8 -*-

# Copyright (C) 2011 Claude Paroz <claude@2xlibre.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
#from django.views.generic import TemplateView

from translator import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(template_name="index.html"), name='home'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.urls')),

    url(r'^series/new/$', views.SeriesCreate.as_view(), name='series_new'),
    url(r'^series/(?P<slug>[\w\-]+)/$', views.SeriesDetail.as_view(), name='series_detail'),
    url(r'^series/(?P<slug>[\w\-]+)/perms/$', views.SeriesPermsView.as_view(), name='series_perms'),
    url(r'^series/(?P<slug>[\w\-]+)/lang/new/$', views.LanguageAdd.as_view(), name='language_add'),
    url(r'^series/(?P<slug>[\w\-]+)/doc/new/$', views.DocumentCreate.as_view(), name='document_new'),
    url(r'^series/(?P<slug>[\w\-]+)/doc/(?P<pk>\d+)/upload/$',
        views.DocumentUpload.as_view(), name='document_upload'),
    url(r'^series/(?P<slug>[\w\-]+)/doc/(?P<pk>\d+)/delete/$',
        views.DocumentDelete.as_view(), name='document_delete'),

    url(r'^series/(?P<slug>[\w\-]+)/doc/(?P<pk>\d+)/lang/(?P<code>\w+)/$',
        views.DocumentDetail.as_view(), name='document_detail'),
    url(r'^series/(?P<slug>[\w\-]+)/doc/(?P<pk>\d+)/lang/(?P<code>\w+)/reserve/(?P<action>(on|off))/$',
        views.DocumentReserve.as_view(), name='document_reserve'),
    url(r'^series/(?P<slug>[\w\-]+)/doc/(?P<doc_pk>\d+)/trans/(?P<trans>\w+)/upload/$',
        views.TranslationUpload.as_view(), name='translation_upload'),
    url(r'^series/(?P<slug>[\w\-]+)/doc/(?P<doc_pk>\d+)/lang/(?P<code>\w+)/img/(?P<pk>\d+)/upload/$',
        views.TransImageUpload.as_view(), name='image_upload'),
    url(r'^series/(?P<slug>[\w\-]+)/doc_image/(?P<pk>\d+)/lang/(?P<code>\w+)/$',
        views.DocumentImageView.as_view(), name='document_image'),

    url(r'^upload_success/(?P<doc_pk>\d+)/$', views.UploadSuccessView.as_view(), name='upload_success'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

translator/models.py
# -*- coding: utf-8 -*-

# Copyright (C) 2011 Claude Paroz <claude@2xlibre.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from datetime import datetime
import os
import re
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files.images import get_image_dimensions
from django.db import models
#from django.db.models.signals import post_save

from translator.fields import UuidField
from translator.storage import OverwriteFSStorage
from translator.utils import run_command

overwrite_fs = OverwriteFSStorage()

class Series(models.Model):
    uuid      = UuidField(auto=True, editable=False)
    title     = models.CharField(max_length=150)
    languages = models.ManyToManyField('Language')

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('series_detail', (), {'slug': self.uuid})

    def is_admin(self, user):
        if user.is_authenticated():
            return self.seriesperm_set.filter(user=user, admin=True).count() > 0
        return False

    def is_translator(self, user):
        if user.is_authenticated():
            return self.seriesperm_set.filter(user=user).count() > 0
        return False

class SeriesPerm(models.Model):
    user  = models.ForeignKey(User)
    obj   = models.ForeignKey(Series)
    admin = models.BooleanField(default=False)

    class Meta:
         unique_together = ("user", "obj")

    def __unicode__(self):
        return u"%s %s for %s" % (
            self.user.username,
            self.admin and "administrator" or "translator",
            self.obj.title)


def doc_upload_path(instance, filename):
    return os.path.join(instance.series.uuid, filename)

class Document(models.Model):
    series    = models.ForeignKey(Series)
    title     = models.CharField(max_length=150)
    original  = models.FileField(upload_to=doc_upload_path, storage=overwrite_fs, verbose_name="Document")
    up_time   = models.DateTimeField(editable=False)
    total_str = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

    def set_upfile(self, uploaded):
        self.original = uploaded
        self.up_time = datetime.now()
        self.save()
        self.update_document()

    def original_fname(self):
        return os.path.basename(self.original.file.name)

    def translation(self, language):
        try:
            return self.translation_set.get(lang=language)
        except Translation.DoesNotExist:
            return None

    def trans_stats(self, language):
        """ Return doc trans statistics as a 4-tuple (trans, fuzzy, untrans, percentage) """
        trans = self.translation(language)
        if trans is None:
            stats = (0, 0, self.total_str, 0)
        else:
            total_str = trans.trans + trans.fuzzy + trans.untrans
            if total_str == 0:
                stats = (0, 0, 0, 0)
            else:
                stats = (trans.trans, trans.fuzzy, trans.untrans,
                    int(trans.trans/float(total_str)*100)
                )
        return stats

    def update_document(self):
        """ Generate a fresh pot file whenever a new document is uploaded,
            Then merge with latest po translation
            Then create translated document
        """
        base, ext = os.path.splitext(self.original_fname())
        series_path = os.path.join(settings.MEDIA_ROOT, self.series.uuid)
        pot_path = os.path.join(series_path, 'pot')
        if not os.path.exists(pot_path):
            os.mkdir(pot_path)
        # The 'cd' is important as it hides the absolute paths in itstool pot output
        run_command("cd %(spath)s && %(path)sitstool -o %(outpot)s %(original)s" % {
            'spath' : series_path,
            'path'  : settings.ITSTOOL_PATH,
            'outpot': os.path.join(pot_path, '%s.pot' % base),
            'original': self.original_fname(),
        }, raise_on_error=True)

        # Update images
        img_dir = os.path.join(pot_path, '%s__images' % base)
        existing = [di.pk for di in self.documentimage_set.all()]
        if os.path.exists(img_dir):
            for img in os.listdir(img_dir):
                if not "." in img:
                    # No extension (probably Object Replacement image)
                    continue
                doc_img, created = DocumentImage.objects.get_or_create(
                    doc=self, fname=img,
                    defaults={'doc':self, 'fname': img})
                if not created:
                    existing.remove(doc_img.pk)
        DocumentImage.objects.filter(pk__in=existing).delete()

        # Get total strings
        (status, output, errs) = run_command("LANG=C msgfmt --statistics -o /dev/null %s" % (
            os.path.join(pot_path, '%s.pot' % base),))
        r_un = re.search(r"([0-9]+) untranslated", errs)
        if r_un:
            self.total_str = int(r_un.group(1))
            self.save()

        # Merge
        for lang in self.series.languages.all():
            trans = self.translation(lang)
            if trans is None:
                continue
            trans.update_translation()


class Language(models.Model):
    code = models.SlugField(max_length=6, unique=True)
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.code)


def po_upload_path(instance, filename):
    return os.path.join(instance.doc.series.uuid, 'po',
        datetime.now().strftime('%Y%m%d-%H%M'), filename)

class Translation(models.Model):
    doc     = models.ForeignKey(Document)
    lang    = models.ForeignKey(Language)
    up_time = models.DateTimeField(auto_now_add=True)
    up_file = models.FileField(upload_to=po_upload_path)
    merged  = models.CharField(max_length=150, null=True) # path to merged file
    trans   = models.SmallIntegerField(default=0)
    fuzzy   = models.SmallIntegerField(default=0)
    untrans = models.SmallIntegerField(default=0)
    reserved_by = models.ForeignKey(User, null=True)
    errors  = models.TextField(blank=True, default='')

    def __unicode__(self):
        return u"%s translation of document '%s'" % (lang.name, doc.title)

    def translated(self):
        """ Returns a path relative to media_root """
        base, ext = os.path.splitext(unicode(self.doc.original))
        path = "%s.%s%s" % (base, self.lang.code, ext)
        if os.path.exists(os.path.join(settings.MEDIA_ROOT, path)):
            return path
        else:
            return None

    def set_upfile(self, uploaded):
        self.up_file = uploaded
        self.up_time = datetime.now()
        self.save()
        self.update_translation()

    def update_translation(self):
        base, ext = os.path.splitext(self.doc.original_fname())
        pot_path = os.path.join(settings.MEDIA_ROOT, self.doc.series.uuid, 'pot')
        po_path = os.path.join(settings.MEDIA_ROOT, str(self.up_file))
        merged_rel_path =  u"%s.merged.po" % str(self.up_file)[:-3]
        run_command("msgmerge --previous -o %(new_po)s %(po)s %(pot)s" % {
            'new_po': os.path.join(settings.MEDIA_ROOT, merged_rel_path),
            'po':     po_path,
            'pot':    os.path.join(pot_path, '%s.pot' % base),
        }, raise_on_error=True)
        self.merged = merged_rel_path

        # Compute stats
        (status, output, errs) = run_command("LANG=C msgfmt --statistics -o /dev/null %s" % (
            os.path.join(settings.MEDIA_ROOT, merged_rel_path),))
        # msgfmt output stats on stderr
        r_tr = re.search(r"([0-9]+) translated", errs)
        r_un = re.search(r"([0-9]+) untranslated", errs)
        r_fz = re.search(r"([0-9]+) fuzzy", errs)
        if r_tr:
            self.trans = int(r_tr.group(1))
        self.untrans = 0
        if r_un:
            self.untrans = int(r_un.group(1))
        self.fuzzy = 0
        if r_fz:
            self.fuzzy = int(r_fz.group(1))
        self.save()

        # Create translated doc
        mo_path = os.path.join(settings.MEDIA_ROOT, "%s.mo" % merged_rel_path[:-3])
        run_command("msgfmt -o %(mo)s %(po)s" % {
            'po': os.path.join(settings.MEDIA_ROOT, merged_rel_path),
            'mo': mo_path,
        }, raise_on_error=True)
        base, ext = os.path.splitext(unicode(self.doc.original))
        final_path = os.path.join(settings.MEDIA_ROOT, "%s.%s%s" % (base, self.lang.code, ext))
        command = "%(path)sitstool -m %(mo)s -I %(img_dir)s -o %(final)s %(current)s" % {
            'path':    settings.ITSTOOL_PATH,
            'mo':      mo_path,
            'img_dir': os.path.join(settings.MEDIA_ROOT, self.doc.series.uuid, 'img'),
            'final':   final_path,
            'current': os.path.join(settings.MEDIA_ROOT, unicode(self.doc.original)),
        }
        try:
            run_command(command, raise_on_error=True)
        except OSError, e:
            self.errors = str(e)
            self.save()
            os.remove(final_path)
            return
        if self.errors:
            self.errors = ""
            self.save()


class DocumentImage(models.Model):
    doc     = models.ForeignKey(Document)
    fname   = models.CharField(max_length=100)

    def img_path(self):
        img_dir = "%s__images" % os.path.splitext(self.doc.original_fname())[0]

translator/forms.py
# -*- coding: utf-8 -*-

# Copyright (C) 2011 Claude Paroz <claude@2xlibre.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from datetime import datetime
import os
from django import forms
from django.contrib.auth.models import User
from django.db import IntegrityError

from translator.models import Series, SeriesPerm, Document, Language
from translator.utils import run_command

class SeriesForm(forms.ModelForm):
    class Meta:
        model = Series
        fields = ('title',)
    first_doc  = forms.FileField(label="First document")

    def save(self):
        super(SeriesForm, self).save()
        doc = Document.objects.create(
            series  = self.instance,
            title   = self.cleaned_data['first_doc'].name,
            original= self.cleaned_data['first_doc'],
            up_time = datetime.now(),
        )
        doc.update_document()
        return self.instance

class AddLanguageForm(forms.Form):
    language = forms.ModelChoiceField(queryset=Language.objects.all().order_by('name'), empty_label=None)

class SeriesPermsForm(forms.Form):
    admin_username = forms.CharField(required=False, widget=forms.TextInput({ "placeholder": "username" }))
    trans_username = forms.CharField(required=False, widget=forms.TextInput({ "placeholder": "username" }))

    def save(self, series):
        try:
            if self.cleaned_data['admin_username']:
                SeriesPerm.objects.create(user=self.admin_username, obj=series, admin=True)
            if self.cleaned_data['trans_username']:
                SeriesPerm.objects.create(user=self.trans_username, obj=series, admin=False)
        except IntegrityError:
            pass

    def check_username(self, field_name):
        if self.cleaned_data[field_name]:
            try:
                setattr(self, field_name, User.objects.get(username=self.cleaned_data[field_name]))
            except User.DoesNotExist:
                raise forms.ValidationError("Username '%s' does not exist in the database." % self.cleaned_data[field_name])
        return self.cleaned_data[field_name]

    def clean_admin_username(self):
        return self.check_username('admin_username')

    def clean_trans_username(self):
        return self.check_username('trans_username')


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('series', 'original')
        widgets = {
            'series': forms.HiddenInput,
        }
    # title as hidden field ? (initially same as filename)

    def save(self):
        self.instance.up_time = datetime.now()
        self.instance.title = self.cleaned_data['original'].name
        doc = super(DocumentForm, self).save()
        doc.update_document()
        return doc

class UploadForm(forms.Form):
    """ File upload form (for different models, model has to define set_upfile method) """
    up_file = forms.FileField()

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop('instance', None)
        super(UploadForm, self).__init__(*args, **kwargs)

    def save(self):
        self.instance.set_upfile(self.cleaned_data['up_file'])
        return self.instance

class PoUploadForm(UploadForm):
    def clean_up_file(self):
        data = self.cleaned_data['up_file']
        if data:
            ext = os.path.splitext(data.name)[1]
            if ext != '.po':
                raise forms.ValidationError("Only files with extension .po are admitted.")
            (status, out, err) = run_command("msgfmt -v --check-format -o /dev/null %s" % data.temporary_file_path())
            if status!=0 and err:
                raise forms.ValidationError(".po file does not pass 'msgfmt -vc'. Please correct the file and try again.")
        return data

templates/translator/document_detail.html
{% extends "base.html" %}
{% load translator %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/colorbox.css"/>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.colorbox-min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $("#images-head").toggle(
    function() {$("#images-body").show('slow'); $("#images-head").attr('class', 'sect-open');},
    function() {$("#images-body").hide(); $("#images-head").attr('class', 'sect-closed');}
  );
  $("a[rel=imgbox]").colorbox();
});
</script>
{% endblock %}

{% block breadcrumb %}Series: <a href="{{ series.get_absolute_url }}">{{ series }}</a>{% endblock %}
{% block title %}
  {% if is_admin %}<div style="float:right; padding-top: 2em;">
    <img src="{{ STATIC_URL }}img/delete.png" onclick="return delete_doc('{% url document_delete series.uuid doc.pk %}', '{{ csrf_token }}');">
    </div>{% endif %}
  <h1>{{ doc.title }}</h1>
{% endblock %}

{% block content %}
<div class="block">
  <div style="float: left; margin-right: 0.3em;"><img src="{{ STATIC_URL}}img/odt.png"></div>
  <em>Original document ({{ doc.total_str}} strings):</em>
  <div style="padding-left: 1em;">{{ doc|doc_original|safe }}</div>
  <div class="note">(uploaded on {{ doc.up_time }})</div>
</div>

<div><img style="margin: 2em 0 2em 12em;" src="{{ STATIC_URL }}img/down_arrow.png"></div>

<div class="block">
  <div style="float: left; margin-right: 0.3em;"><img src="{{ STATIC_URL}}img/generic.png"></div>
  {% if is_translator %}
  <div style="float:right"><a href="{% url translation_upload series.uuid doc.pk trans_pk %}" class="button" title="Upload a translated po file">Upload</a></div>
  {% endif %}
  <div style="float:left">
    <em>Translation file:</em>
    <div style="padding-left: 1em;">{{ doc|doc_translation:language|safe }}</div>
    {% if not trans == None %}
    <div class="note">(uploaded on {{ trans.up_time }})</div>
    {% endif %}
  </div>

  <div style="float:left; margin-left: 2em;">
    <div style="color: #666666; font-size: 200%">{{ doc|show_stats:language|safe }}</div>
    <div style="margin-top: 0.5em; text-align: center;">
      {% if trans == None or not trans.reserved_by %}
        {% if is_translator %}<a class="button" href="." onclick="return reserve_trans('{% url document_reserve series.uuid doc.pk language.code 'on' %}', '{{ csrf_token }}')">Reserve Translation</a>{% endif %}
      {% else %}
        {% if trans.reserved_by == user %}
          <div class="messages">You have reserved this document.</div>
          <div style="margin: 0.5em 0;">
            <a class="button" href="." onclick="return reserve_trans('{% url document_reserve series.uuid doc.pk language.code 'off' %}', '{{ csrf_token }}')">Release Translation</a>
          </div>
        {% else %}<div class="messages">{{ user }} has reserved this document.</div>
        {% endif %}
      {% endif %}
    </div>
  </div>

  <div style="float:left; margin-left: 2em;">
    {% if images|length > 0 %}
    <div id="images-head" class="sect-closed"><em>Images ({{ images|length }}):</em></div>
    {% else %}
    <div><em>no images</em></div>
    {% endif %}
    <div id="images-body" style="display:none;">
    {% for img in images %}
      <div style="clear:left;">
        <a id="thumb_{{ img.id }}" href="{% url document_image series.uuid img.pk language.code %}"
           rel="imgbox" title="{{ img.fname }} ({{ img.img_dimensions.0 }}x{{ img.img_dimensions.1 }})">
          {{ img|as_thumbnail|safe }}
        </a>
      </div>
    {% endfor %}
    </div>
  </div>
  <div style="clear:both">
    {% if trans and trans.errors %}
    <div class="errors"><img src="{{ STATIC_URL }}img/warn.png"> The translation file contains errors
      <div class="error_message">{{ trans.errors }}</div>
    </div>
    {% endif %}
  </div>
</div>

<div><img style="margin: 2em 0 2em 12em;" src="{{ STATIC_URL }}img/down_arrow.png"></div>

<div class="block">
  <div style="float: left; margin-right: 0.3em;"><img src="{{ STATIC_URL}}img/odt.png"></div>
  <em>Translated document:</em>
  <div style="padding-left: 1em;">{{ trans|translated_doc|safe }}</div>
</div>
{% endblock %}

templates/translator/document_form.html
{% extends "base.html" %}

{% block breadcrumb %}Series: <a href="{{ series.get_absolute_url }}">{{ series }}</a>{% endblock %}
{% block title %}<h1>{% if object.pk %}Upload{% else %}Add{% endif %} new Document</h1>{% endblock %}

{% block content %}
<form action="." enctype="multipart/form-data" method="post" style="padding-left: 2em;">
  {% csrf_token %}
  <table class="form">
  {{ form.as_table }}
  </table>
  <input type="submit" value="{% if object.pk %}Upload{% else %}Add{% endif %}">
</form>
{% endblock %}

templates/translator/document_image.html
{% load translator %}
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css"/>
  <style TYPE="text/css">
    <!--
    img { border: 1px dotted gray; }
    -->
  </style>
  <script type="text/javascript" src="{{ STATIC_URL }}js/translator.js"></script>
</head>

<body>
<table id="cbox"><tr>
    <td width="50%"><img src="{{ img.img_url }}"></td>
    <td width="50%" align="center" valign="center">{% if img.translation = None %}
        <img src="{{ STATIC_URL }}img/cross.png" {{ img|cross_dim }}>
        {% else %}
        <img src="{{ img.translation.img_url }}">
        {% endif %}
    </td>
</tr>
<tr>
    <td><!--<input type="checkbox"> This image does not need translation--></td>
    <td>{% if translator %}
        <em>{% if img.translation = None %}<a href="{{ upload_link }}" onclick="return open_upload(this);">upload image...</a>
            {% else %}<a href="{{ upload_link }}" onclick="return open_upload(this);">upload new...</a>
            {% endif %}
        </em>
        {% endif %}
    </td>
</tr></table>
</body>
</html>

templates/translator/document_upform.html
{% extends "base.html" %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/colorbox.css"/>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.colorbox-min.js"></script>
{% endblock %}
{% block breadcrumb %}Series: <a href="{{ series.get_absolute_url }}">{{ series }}</a>{% endblock %}
{% block title %}<h1>Upload new File</h1>{% endblock %}

{% block content %}
<form action="." enctype="multipart/form-data" method="post" style="padding-left: 2em;">
  {% csrf_token %}
  <table class="form">
  {{ form.up_file.errors }}{{ form.up_file }}
  </table>
  <input type="submit" value="Upload">
</form>
{% endblock %}

templates/translator/language_add.html
{% extends "base.html" %}

{% block breadcrumb %}Series: <a href="{{ series.get_absolute_url }}">{{ series }}</a>{% endblock %}
{% block title %}<h1>Add new Language</h1>{% endblock %}

{% block content %}
<form action="." method="post">
  {% csrf_token %}
  <table class="form">
  {{ form.as_table }}
  </table>
  <input type="submit" value="Add">
</form>
{% endblock %}

templates/translator/series_detail.html
{% extends "base.html" %}
{% load translator %}

{% block breadcrumb %}{% endblock %}
{% block title %}<h1>{{ series.title }}</h1>{% endblock %}

{% block content %}
<p>This series contains the following document(s):</p>
<table class="list">
  <thead><tr><td></td>
      {% for lang in languages %}
      <th>{{ lang.name }}</th>
      {% endfor %}
  </tr></thead>
  <tbody>
{% for doc in documents %}
  <tr class="{% cycle 'odd' '' %}">
      <td>&bull; {{ doc }}
          <div class="note" style="margin-left: 1em;">(uploaded on {{ doc.up_time }})</div>
      </td>
      {% for lang in languages %}
      <td><a href="{% url document_detail series.uuid doc.id lang.code %}">{{ doc|show_stats:lang|safe }}</a>
          {{ doc|reserved_by:lang|safe }}
      </td>
      {% endfor %}
      {% if is_admin %}
      <td><a href="{% url document_upload series.uuid doc.pk %}" class="button" title="Upload a new version of the same document">Upload</a></td>
      {% endif %}
  </tr>
{% endfor %}
  </tbody>
</table>
{% if is_admin %}
<div style="margin-top:1em; float: right;"><a href="{% url series_perms series.uuid %}">Permissions…</a></div>
<div style="margin-top:1em;">
    <a class="button" href="{% url document_new series.uuid %}">Add a document…</a>
    <a class="button" href="{% url language_add series.uuid %}">Add a language…</a>
</div>
{% endif %}

{% endblock %}

templates/translator/series_form.html
{% extends "base.html" %}

{% block extra_head %}
<style TYPE="text/css">
<!--
  input#id_title {
    width: 30em;
  }
-->
</style>
{% endblock %}

{% block title %}<h1>Create new Series</h1>{% endblock %}

{% block content %}
<form action="." enctype="multipart/form-data" method="post" style="padding-left: 2em;">
  {% csrf_token %}
  <table class="form">
  {{ form.as_table }}
  </table>
  <p>Note that you will be able to add more document to this series in later steps.</p>
  <input type="submit" value="Create">
</form>
{% endblock %}

templates/translator/series_perms.html
{% extends "base.html" %}
{% load translator %}

{% block breadcrumb %}Series: <a href="{{ series.get_absolute_url }}">{{ series }}</a>{% endblock %}
{% block title %}<h1>{{ series.title }} - Permissions</h1>{% endblock %}

{% block content %}

<form action="." method="post">
{% csrf_token %}
<div style="float:left; margin-left: 1em;">
  <div style="padding: 0.3em; border: 1px solid #D9D9D9;">
  <h2>Administrators</h2>
  <ul>
    {% for pers in admins %}
    <li>{{ pers|disp_user }}</li>
    {% endfor %}
  </ul>
  </div>
  {% if is_admin %}
  <div>{{ form.admin_username.errors }}{{ form.admin_username }} <input type="submit" value="Add"></div>
  {% endif %}
</div>

<div style="float:left; margin-left: 1em;">
  <div style="padding: 0.3em; border: 1px solid #D9D9D9;">
  <h2>Translators</h2>
  <ul>
    {% for pers in translators %}
    <li>{{ pers|disp_user }}</li>
    {% endfor %}
  </ul>
  </div>
  {% if is_admin %}
  <div>{{ form.trans_username.errors }}{{ form.trans_username }} <input type="submit" value="Add"></div>
  {% endif %}
</div>
</form>
{% endblock %}

templates/translator/upload_success.html
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.6.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    if (window.opener) {
        window.opener.$.fn.colorbox.load();
        setTimeout(function() { window.opener.$.fn.colorbox.load(); }, 200);
        setTimeout(window.close, 250);
        // Update thumbnails on main page
        $('#thumb_{{ img_id }}', window.opener.document).html('{{ data|safe }}');
    }
});
</script>
</head>
<body>File successfully uploaded</body>
</html>